### PR TITLE
Fixed some bugs

### PR DESCRIPTION
**Pull request by Trevelopment**
* Fixed always playing first video when shuffle is off
* Fixed cutting off last second of video
* Fixed not able to FF in final 35 seconds now just final 12 seconds
* Added localStorage code (commented out but I tested it and it works)

Would be interested to see if localStorage works for you without the mod.

### CODE REVIEW

**Comment by vicbam85** [comment]
Please update your brach from mine. I just finished testing your changes and updated mine. I've seen you have erased some lines related to the videoplayback button and fullscreen buttons. That may be your problem.

I'm testing the localstorage function

**Comment by Trevelopment** [comment]
Awesome, let me know how it goes.  If it doesnt work I can show you what needs to be done to make it work, its pretty simple just one file in opera_home folder and make a storage folder in persistant_data.
Oh and I wasn't having that problem anymore but thanks.

**Comment by Trevelopment** [comment]
Wait, did you say I erased some lines? what lines did I erase I don't see where?

**Comment by Trevelopment** [comment]
Well let me know, I'm going to close this because I made another pull request because I forgot that the checkboxes need to update if they should be checked so you can see if it is working or not.

**Pull request closed without merging**
